add argc verification

diff --git a/select4sh b/select4sh
--- a/select4sh
+++ b/select4sh
@@ -43,6 +43,14 @@ done
 shift $((OPTIND - 1))
 
 ####################################
+##### Verification #################
+####################################
+if [[ $# -eq 0 ]]; then
+	echo "Error: Options are needed." > "$tty"
+	exit 1
+fi
+
+####################################
 ##### Main #########################
 ####################################
 {
